/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateBoardMemberArgs = IDL.Record({
  'bio' : IDL.Text,
  'linkedIn' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const BoardMemberId = IDL.Nat;
export const BoardMember = IDL.Record({
  'id' : BoardMemberId,
  'bio' : IDL.Text,
  'linkedIn' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const CreateBrandArgs = IDL.Record({
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sector' : IDL.Text,
  'website' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const BrandId = IDL.Nat;
export const Brand = IDL.Record({
  'id' : BrandId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sector' : IDL.Text,
  'website' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const JobType = IDL.Variant({
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const CreateJobArgs = IDL.Record({
  'title' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const JobId = IDL.Nat;
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const FirmInfo = IDL.Record({
  'missionStatement' : IDL.Text,
  'statsJson' : IDL.Text,
  'heroCopy' : IDL.Text,
  'investmentStrategy' : IDL.Text,
  'heroHeadline' : IDL.Text,
});
export const ApplicationId = IDL.Nat;
export const Timestamp = IDL.Int;
export const JobApplication = IDL.Record({
  'id' : ApplicationId,
  'applicantName' : IDL.Text,
  'jobId' : JobId,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ContactSubmissionId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactSubmissionId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SubmitApplicationArgs = IDL.Record({
  'applicantName' : IDL.Text,
  'jobId' : JobId,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SubmitContactArgs = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UpdateBoardMemberArgs = IDL.Record({
  'id' : BoardMemberId,
  'bio' : IDL.Text,
  'linkedIn' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const UpdateBrandArgs = IDL.Record({
  'id' : BrandId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sector' : IDL.Text,
  'website' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const UpdateFirmInfoArgs = IDL.Record({
  'missionStatement' : IDL.Text,
  'statsJson' : IDL.Text,
  'heroCopy' : IDL.Text,
  'investmentStrategy' : IDL.Text,
  'heroHeadline' : IDL.Text,
});
export const UpdateJobArgs = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBoardMember' : IDL.Func([CreateBoardMemberArgs], [BoardMember], []),
  'createBrand' : IDL.Func([CreateBrandArgs], [Brand], []),
  'createJob' : IDL.Func([CreateJobArgs], [Job], []),
  'deleteBoardMember' : IDL.Func([BoardMemberId], [IDL.Bool], []),
  'deleteBrand' : IDL.Func([BrandId], [IDL.Bool], []),
  'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
  'getBoardMember' : IDL.Func(
      [BoardMemberId],
      [IDL.Opt(BoardMember)],
      ['query'],
    ),
  'getBrand' : IDL.Func([BrandId], [IDL.Opt(Brand)], ['query']),
  'getFirmInfo' : IDL.Func([], [FirmInfo], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'listActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'listApplicationsForJob' : IDL.Func(
      [JobId],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'listBoardMembers' : IDL.Func([], [IDL.Vec(BoardMember)], ['query']),
  'listBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'submitApplication' : IDL.Func([SubmitApplicationArgs], [JobApplication], []),
  'submitContact' : IDL.Func([SubmitContactArgs], [ContactSubmission], []),
  'updateBoardMember' : IDL.Func(
      [UpdateBoardMemberArgs],
      [IDL.Opt(BoardMember)],
      [],
    ),
  'updateBrand' : IDL.Func([UpdateBrandArgs], [IDL.Opt(Brand)], []),
  'updateFirmInfo' : IDL.Func([UpdateFirmInfoArgs], [FirmInfo], []),
  'updateJob' : IDL.Func([UpdateJobArgs], [IDL.Opt(Job)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateBoardMemberArgs = IDL.Record({
    'bio' : IDL.Text,
    'linkedIn' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const BoardMemberId = IDL.Nat;
  const BoardMember = IDL.Record({
    'id' : BoardMemberId,
    'bio' : IDL.Text,
    'linkedIn' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const CreateBrandArgs = IDL.Record({
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sector' : IDL.Text,
    'website' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const BrandId = IDL.Nat;
  const Brand = IDL.Record({
    'id' : BrandId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sector' : IDL.Text,
    'website' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const JobType = IDL.Variant({
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const CreateJobArgs = IDL.Record({
    'title' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobId = IDL.Nat;
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const FirmInfo = IDL.Record({
    'missionStatement' : IDL.Text,
    'statsJson' : IDL.Text,
    'heroCopy' : IDL.Text,
    'investmentStrategy' : IDL.Text,
    'heroHeadline' : IDL.Text,
  });
  const ApplicationId = IDL.Nat;
  const Timestamp = IDL.Int;
  const JobApplication = IDL.Record({
    'id' : ApplicationId,
    'applicantName' : IDL.Text,
    'jobId' : JobId,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ContactSubmissionId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactSubmissionId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SubmitApplicationArgs = IDL.Record({
    'applicantName' : IDL.Text,
    'jobId' : JobId,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SubmitContactArgs = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UpdateBoardMemberArgs = IDL.Record({
    'id' : BoardMemberId,
    'bio' : IDL.Text,
    'linkedIn' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const UpdateBrandArgs = IDL.Record({
    'id' : BrandId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sector' : IDL.Text,
    'website' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const UpdateFirmInfoArgs = IDL.Record({
    'missionStatement' : IDL.Text,
    'statsJson' : IDL.Text,
    'heroCopy' : IDL.Text,
    'investmentStrategy' : IDL.Text,
    'heroHeadline' : IDL.Text,
  });
  const UpdateJobArgs = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'createBoardMember' : IDL.Func([CreateBoardMemberArgs], [BoardMember], []),
    'createBrand' : IDL.Func([CreateBrandArgs], [Brand], []),
    'createJob' : IDL.Func([CreateJobArgs], [Job], []),
    'deleteBoardMember' : IDL.Func([BoardMemberId], [IDL.Bool], []),
    'deleteBrand' : IDL.Func([BrandId], [IDL.Bool], []),
    'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
    'getBoardMember' : IDL.Func(
        [BoardMemberId],
        [IDL.Opt(BoardMember)],
        ['query'],
      ),
    'getBrand' : IDL.Func([BrandId], [IDL.Opt(Brand)], ['query']),
    'getFirmInfo' : IDL.Func([], [FirmInfo], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'listActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'listApplicationsForJob' : IDL.Func(
        [JobId],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'listBoardMembers' : IDL.Func([], [IDL.Vec(BoardMember)], ['query']),
    'listBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'submitApplication' : IDL.Func(
        [SubmitApplicationArgs],
        [JobApplication],
        [],
      ),
    'submitContact' : IDL.Func([SubmitContactArgs], [ContactSubmission], []),
    'updateBoardMember' : IDL.Func(
        [UpdateBoardMemberArgs],
        [IDL.Opt(BoardMember)],
        [],
      ),
    'updateBrand' : IDL.Func([UpdateBrandArgs], [IDL.Opt(Brand)], []),
    'updateFirmInfo' : IDL.Func([UpdateFirmInfoArgs], [FirmInfo], []),
    'updateJob' : IDL.Func([UpdateJobArgs], [IDL.Opt(Job)], []),
  });
};

export const init = ({ IDL }) => { return []; };