/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationId = bigint;
export interface BoardMember {
  'id' : BoardMemberId,
  'bio' : string,
  'linkedIn' : string,
  'title' : string,
  'order' : bigint,
  'name' : string,
  'photoUrl' : string,
}
export type BoardMemberId = bigint;
export interface Brand {
  'id' : BrandId,
  'order' : bigint,
  'name' : string,
  'description' : string,
  'sector' : string,
  'website' : string,
  'logoUrl' : string,
}
export type BrandId = bigint;
export interface ContactSubmission {
  'id' : ContactSubmissionId,
  'subject' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export type ContactSubmissionId = bigint;
export interface CreateBoardMemberArgs {
  'bio' : string,
  'linkedIn' : string,
  'title' : string,
  'order' : bigint,
  'name' : string,
  'photoUrl' : string,
}
export interface CreateBrandArgs {
  'order' : bigint,
  'name' : string,
  'description' : string,
  'sector' : string,
  'website' : string,
  'logoUrl' : string,
}
export interface CreateJobArgs {
  'title' : string,
  'jobType' : JobType,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'location' : string,
}
export interface FirmInfo {
  'missionStatement' : string,
  'statsJson' : string,
  'heroCopy' : string,
  'investmentStrategy' : string,
  'heroHeadline' : string,
}
export interface Job {
  'id' : JobId,
  'title' : string,
  'jobType' : JobType,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'location' : string,
}
export interface JobApplication {
  'id' : ApplicationId,
  'applicantName' : string,
  'jobId' : JobId,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export type JobId = bigint;
export type JobType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface SubmitApplicationArgs {
  'applicantName' : string,
  'jobId' : JobId,
  'email' : string,
  'message' : string,
}
export interface SubmitContactArgs {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export type Timestamp = bigint;
export interface UpdateBoardMemberArgs {
  'id' : BoardMemberId,
  'bio' : string,
  'linkedIn' : string,
  'title' : string,
  'order' : bigint,
  'name' : string,
  'photoUrl' : string,
}
export interface UpdateBrandArgs {
  'id' : BrandId,
  'order' : bigint,
  'name' : string,
  'description' : string,
  'sector' : string,
  'website' : string,
  'logoUrl' : string,
}
export interface UpdateFirmInfoArgs {
  'missionStatement' : string,
  'statsJson' : string,
  'heroCopy' : string,
  'investmentStrategy' : string,
  'heroHeadline' : string,
}
export interface UpdateJobArgs {
  'id' : JobId,
  'title' : string,
  'jobType' : JobType,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'location' : string,
}
export interface _SERVICE {
  'createBoardMember' : ActorMethod<[CreateBoardMemberArgs], BoardMember>,
  'createBrand' : ActorMethod<[CreateBrandArgs], Brand>,
  'createJob' : ActorMethod<[CreateJobArgs], Job>,
  'deleteBoardMember' : ActorMethod<[BoardMemberId], boolean>,
  'deleteBrand' : ActorMethod<[BrandId], boolean>,
  'deleteJob' : ActorMethod<[JobId], boolean>,
  'getBoardMember' : ActorMethod<[BoardMemberId], [] | [BoardMember]>,
  'getBrand' : ActorMethod<[BrandId], [] | [Brand]>,
  'getFirmInfo' : ActorMethod<[], FirmInfo>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'listActiveJobs' : ActorMethod<[], Array<Job>>,
  'listApplications' : ActorMethod<[], Array<JobApplication>>,
  'listApplicationsForJob' : ActorMethod<[JobId], Array<JobApplication>>,
  'listBoardMembers' : ActorMethod<[], Array<BoardMember>>,
  'listBrands' : ActorMethod<[], Array<Brand>>,
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'submitApplication' : ActorMethod<[SubmitApplicationArgs], JobApplication>,
  'submitContact' : ActorMethod<[SubmitContactArgs], ContactSubmission>,
  'updateBoardMember' : ActorMethod<
    [UpdateBoardMemberArgs],
    [] | [BoardMember]
  >,
  'updateBrand' : ActorMethod<[UpdateBrandArgs], [] | [Brand]>,
  'updateFirmInfo' : ActorMethod<[UpdateFirmInfoArgs], FirmInfo>,
  'updateJob' : ActorMethod<[UpdateJobArgs], [] | [Job]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];