/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface SubmitApplicationArgs {
    applicantName: string;
    jobId: JobId;
    email: string;
    message: string;
}
export type ContactSubmissionId = bigint;
export interface ContactSubmission {
    id: ContactSubmissionId;
    subject: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
}
export interface BoardMember {
    id: BoardMemberId;
    bio: string;
    linkedIn: string;
    title: string;
    order: bigint;
    name: string;
    photoUrl: string;
}
export interface UpdateBrandArgs {
    id: BrandId;
    order: bigint;
    name: string;
    description: string;
    sector: string;
    website: string;
    logoUrl: string;
}
export interface SubmitContactArgs {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export type JobId = bigint;
export interface UpdateBoardMemberArgs {
    id: BoardMemberId;
    bio: string;
    linkedIn: string;
    title: string;
    order: bigint;
    name: string;
    photoUrl: string;
}
export interface JobApplication {
    id: ApplicationId;
    applicantName: string;
    jobId: JobId;
    submittedAt: Timestamp;
    email: string;
    message: string;
}
export interface FirmInfo {
    missionStatement: string;
    statsJson: string;
    heroCopy: string;
    investmentStrategy: string;
    heroHeadline: string;
}
export interface CreateBrandArgs {
    order: bigint;
    name: string;
    description: string;
    sector: string;
    website: string;
    logoUrl: string;
}
export interface Brand {
    id: BrandId;
    order: bigint;
    name: string;
    description: string;
    sector: string;
    website: string;
    logoUrl: string;
}
export interface UpdateFirmInfoArgs {
    missionStatement: string;
    statsJson: string;
    heroCopy: string;
    investmentStrategy: string;
    heroHeadline: string;
}
export interface Job {
    id: JobId;
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}
export interface CreateBoardMemberArgs {
    bio: string;
    linkedIn: string;
    title: string;
    order: bigint;
    name: string;
    photoUrl: string;
}
export interface CreateJobArgs {
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}
export type BrandId = bigint;
export type ApplicationId = bigint;
export interface UpdateJobArgs {
    id: JobId;
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}
export type BoardMemberId = bigint;
export enum JobType {
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export interface backendInterface {
    createBoardMember(args: CreateBoardMemberArgs): Promise<BoardMember>;
    createBrand(args: CreateBrandArgs): Promise<Brand>;
    createJob(args: CreateJobArgs): Promise<Job>;
    deleteBoardMember(id: BoardMemberId): Promise<boolean>;
    deleteBrand(id: BrandId): Promise<boolean>;
    deleteJob(id: JobId): Promise<boolean>;
    getBoardMember(id: BoardMemberId): Promise<BoardMember | null>;
    getBrand(id: BrandId): Promise<Brand | null>;
    getFirmInfo(): Promise<FirmInfo>;
    getJob(id: JobId): Promise<Job | null>;
    listActiveJobs(): Promise<Array<Job>>;
    listApplications(): Promise<Array<JobApplication>>;
    listApplicationsForJob(jobId: JobId): Promise<Array<JobApplication>>;
    listBoardMembers(): Promise<Array<BoardMember>>;
    listBrands(): Promise<Array<Brand>>;
    listContactSubmissions(): Promise<Array<ContactSubmission>>;
    listJobs(): Promise<Array<Job>>;
    submitApplication(args: SubmitApplicationArgs): Promise<JobApplication>;
    submitContact(args: SubmitContactArgs): Promise<ContactSubmission>;
    updateBoardMember(args: UpdateBoardMemberArgs): Promise<BoardMember | null>;
    updateBrand(args: UpdateBrandArgs): Promise<Brand | null>;
    updateFirmInfo(args: UpdateFirmInfoArgs): Promise<FirmInfo>;
    updateJob(args: UpdateJobArgs): Promise<Job | null>;
}
import type { BoardMember as _BoardMember, Brand as _Brand, CreateJobArgs as _CreateJobArgs, Job as _Job, JobId as _JobId, JobType as _JobType, UpdateJobArgs as _UpdateJobArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBoardMember(arg0: CreateBoardMemberArgs): Promise<BoardMember> {
        if (this.processError) {
            try {
                const result = await this.actor.createBoardMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBoardMember(arg0);
            return result;
        }
    }
    async createBrand(arg0: CreateBrandArgs): Promise<Brand> {
        if (this.processError) {
            try {
                const result = await this.actor.createBrand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBrand(arg0);
            return result;
        }
    }
    async createJob(arg0: CreateJobArgs): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_CreateJobArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Job_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_CreateJobArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Job_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBoardMember(arg0: BoardMemberId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBoardMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBoardMember(arg0);
            return result;
        }
    }
    async deleteBrand(arg0: BrandId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBrand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBrand(arg0);
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getBoardMember(arg0: BoardMemberId): Promise<BoardMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardMember(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardMember(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrand(arg0: BrandId): Promise<Brand | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrand(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrand(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFirmInfo(): Promise<FirmInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirmInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirmInfo();
            return result;
        }
    }
    async getJob(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveJobs();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveJobs();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplications();
            return result;
        }
    }
    async listApplicationsForJob(arg0: JobId): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplicationsForJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplicationsForJob(arg0);
            return result;
        }
    }
    async listBoardMembers(): Promise<Array<BoardMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBoardMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBoardMembers();
            return result;
        }
    }
    async listBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBrands();
            return result;
        }
    }
    async listContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactSubmissions();
            return result;
        }
    }
    async listJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitApplication(arg0: SubmitApplicationArgs): Promise<JobApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0);
            return result;
        }
    }
    async submitContact(arg0: SubmitContactArgs): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async updateBoardMember(arg0: UpdateBoardMemberArgs): Promise<BoardMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBoardMember(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBoardMember(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBrand(arg0: UpdateBrandArgs): Promise<Brand | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrand(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrand(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFirmInfo(arg0: UpdateFirmInfoArgs): Promise<FirmInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFirmInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFirmInfo(arg0);
            return result;
        }
    }
    async updateJob(arg0: UpdateJobArgs): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_UpdateJobArgs_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_UpdateJobArgs_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_JobType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Brand]): Brand | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BoardMember]): BoardMember | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    title: string;
    jobType: _JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}): {
    id: JobId;
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        jobType: from_candid_JobType_n7(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        isActive: value.isActive,
        department: value.department,
        location: value.location
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): JobType {
    return "contract" in value ? JobType.contract : "partTime" in value ? JobType.partTime : "fullTime" in value ? JobType.fullTime : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateJobArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobArgs): _CreateJobArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobArgs_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobArgs): _UpdateJobArgs {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobId;
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}): {
    id: _JobId;
    title: string;
    jobType: _JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        isActive: value.isActive,
        department: value.department,
        location: value.location
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    jobType: JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}): {
    title: string;
    jobType: _JobType;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
} {
    return {
        title: value.title,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        isActive: value.isActive,
        department: value.department,
        location: value.location
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == JobType.contract ? {
        contract: null
    } : value == JobType.partTime ? {
        partTime: null
    } : value == JobType.fullTime ? {
        fullTime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
